### ISSUE TITLE
[Feature Request]: Configuration File

### ISSUE THREAD

**Issue by shuzijun** [rytswd/comvent#183]
### Enhancement Area

Comvent Configuration YAML

### Details

The value of the configuration file can be obtained from the secret.

**Comment by rytswd** [comment]
Hi @shuzijun, thanks for filing a feature request! Would you be able to elaborate what you want from the secret? Is it that you want to allow the use of GitHub repository secret for the `keywords[*].value`? If so, what do you think about providing a different key such as `keywords[*].secretName`?

**Comment by shuzijun** [comment]
Sorry, I didn’t understand the question of the last sentence. The configuration I expect is for example:
```
version: 0.2.0

trigger: default

keywords:
  - name: some-abusive-content
    value: ${{secrets.key1}}
  - name: advertising
    value: ${{secrets.key2}}
```

**Comment by rytswd** [comment]
Thanks, I see what you mean now! I originally meant something like below:

```yaml
version: 0.2.0

trigger: default

keywords:
  - name: some-abusive-content
    secretName: SOME_SECRET_FOR_ABUSIVE_CONTENT
  - name: advertising
    secretName: SOME_SECRET_FOR_ADVERTISING_CONTENT
```

The above approach I proposed is probably simpler to implement, but your suggestion is more GitHub Action-like 👍
