### ISSUE TITLE
Comvent ⚡️ Playground 🏞

### ISSUE THREAD

**Issue by rytswd** [rytswd/comvent#24]
## 🔎 About

This is only a playground 🏞
You can comment on this to see Comvent in action, which uses https://github.com/actions/github-script.

## 📝 Note

Because GitHub Action takes several seconds to initiate the action, you may see up to 1 min delay.

#### For all users

- `/weather`: automation responds with a comment
- `/hello-world`: automation responds with a comment

Ref: https://github.com/rytswd/comvent/blob/main/.github/workflows/issue-comment-blacklist-demo.yaml

#### For specific users

- `/random`: automation responds with a comment
- `/today`: automation responds with a comment
- `/httpbin`: automation responds with a comment

Ref: https://github.com/rytswd/comvent/blob/main/.github/workflows/issue-comment-whitelist-demo.yaml

#### Abuse Monitor

- `some abusive content`: If you write a comment including this exact phrase in a single line, you will see the comment being removed via the automation. You will also see a comment about the comment deletion.

Ref: https://github.com/rytswd/comvent/blob/main/.github/workflows/abusive-comment-demo.yaml

**Comment by rytswd** [comment]
This includes some abusive content!

**Comment by lgmorand** [comment]
test

**Comment by rytswd** [comment]
Thanks for checking out, and it does look like something is not functioning correctly when comment is edited, perhaps... 😥
I'll check more into this in the coming days, and will get back to the thread.

For now, this is another test.

/random

**Comment by rytswd** [comment]
Hi @lgmorand - I think your earlier attempt didn't match the comvent setup, because you were triggering the command for "specific" user setup, which is triggered only for whitelisted user list (in this case it only has myself @rytswd listed).

If you instead trigger with comment such as `/weather` or `/hello-world`, it should work and you get some automation in action!

**Comment by rytswd** [comment]
Thanks! It's a good point, I added a TL;DR section 😆

**Comment by rytswd** [comment]
/echo this is test, it may fail due to the job condition.

**Comment by rytswd** [comment]
/echo this is another test.

There was an error with the job condition.

**Comment by rytswd** [comment]
/echo this is another test, this time the response will look up the string correctly.

**Comment by iam-py-test** [comment]
some abusive content

**Comment by iam-py-test** [comment]
some abusive content 2.0

**Comment by iam-py-test** [comment]
@rytswd is there a way to mention the name of the person from the original comment?

**Comment by rytswd** [comment]
@iam-py-test
Do you mean to put the username along with the comment from `github-actions` above?
If so, you can write the original comment sender by `${{ github.event.sender.login }}` as a part of GitHub Action step. This is something that GitHub provides, which you can find more in https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment 👍

Comvent itself does not keep hold of the username in its output. If there is a use case for that, it would be great if you can provide more details and background in a separate issue, so that it can be considered for future enhancements ☺️

**Comment by iam-py-test** [comment]
> @iam-py-test
> Do you mean to put the username along with the comment from `github-actions` above?
> If so, you can write the original comment sender by `${{ github.event.sender.login }}` as a part of GitHub Action step. This is something that GitHub provides, which you can find more in https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment 👍
> 
> Comvent itself does not keep hold of the username in its output. If there is a use case for that, it would be great if you can provide more details and background in a separate issue, so that it can be considered for future enhancements ☺️

Ok, thanks

**Comment by iam-py-test** [comment]
Please forgive me for not knowing, but does anyone know how to install this? 
I tried the instructions & it did not work.
Thanks!

**Comment by rytswd** [comment]
@iam-py-test
Sorry for the delayed response, what sort of error did you get from the instruction? (and which instruction did you follow?)

The installation should be straightforward GitHub Action usage, something like:

```yaml
jobs:
  chatbot:
    name: ChatBot
    runs-on: ubuntu-latest

    steps:
      - name: Handle with Comvent
        uses: rytswd/comvent@v0.4 # Latest available as of now
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comvent-chatbot.yaml # Assumes this file exists
```

If you could provide a bit more detail, I should be able to assist you further 👍

**Comment by iam-py-test** [comment]
> @iam-py-test
> Sorry for the delayed response, what sort of error did you get from the instruction? (and which instruction did you follow?)
> 
> The installation should be straightforward GitHub Action usage, something like:
> 
> ```yaml
> jobs:
>   chatbot:
>     name: ChatBot
>     runs-on: ubuntu-latest
> 
>     steps:
>       - name: Handle with Comvent
>         uses: rytswd/comvent@v0.4 # Latest available as of now
>         id: comvent
>         with:
>           token: ${{ secrets.GITHUB_TOKEN }}
>           config-path: .github/comvent-chatbot.yaml # Assumes this file exists
> ```
> 
> If you could provide a bit more detail, I should be able to assist you further 👍

Ok! @rytswd Thanks! I think I just misunderstood something!

**Comment by iam-py-test** [comment]
@rytswd When I tried it, I got this error:
![image](https://user-images.githubusercontent.com/84232764/121232531-b3dd3880-c85f-11eb-84b6-8d2aae2b395c.png)

Sorry I did not respond earlier; I was busy.

**Comment by iam-py-test** [comment]
> Command `/weather` was triggered by the comment

test

**Comment by iam-py-test** [comment]
> /weather

**Comment by rytswd** [comment]
If you are referring to getting an error with https://github.com/iam-py-test/my_filters_001/blob/main/.github/workflows/comment.yml, it doesn't look to conform to GitHub Actions requirements (i.e. missing `on` stanza, etc.). I'd suggest checking out GitHub Actions documentation for the actual spec.

If you want to simply get the same result as this repo's example, I suggest you check out the setup here
https://github.com/rytswd/comvent/blob/main/.github/workflows/issue-comment-blacklist-demo.yaml

**Comment by iam-py-test** [comment]
> If you are referring to getting an error with https://github.com/iam-py-test/my_filters_001/blob/main/.github/workflows/comment.yml, it doesn't look to conform to GitHub Actions requirements (i.e. missing `on` stanza, etc.). I'd suggest checking out GitHub Actions documentation for the actual spec.
> 
> If you want to simply get the same result as this repo's example, I suggest you check out the setup here
> https://github.com/rytswd/comvent/blob/main/.github/workflows/issue-comment-blacklist-demo.yaml

Ok! Will do.
Thank you for your help

**Comment by iam-py-test** [comment]
I tried that and I get this error:
![image](https://user-images.githubusercontent.com/84232764/121235729-2b609700-c863-11eb-8a95-88d63a381d58.png)

Thanks for your help

**Comment by rytswd** [comment]
Apologies, I should have been clearer - you cannot copy directly from the aforementioned file, as this repo does not pull in the GitHub Action spec but builds itself in the action setup. You need to combine the file content with the setup mentioned here:
https://github.com/rytswd/comvent/issues/24#issuecomment-856888939

You can see a complete example here https://github.com/rytswd/comvent#chatbot-setup, by clicking on `Click to view full example`. (Note that this refers to v0.3)

```yaml
name: ChatBot
on:
  issue_comment:
    # This shouldn't be called for comment deletion
    types:
      - created
      - edited

jobs:
  chatbot:
    name: With latest code base
    runs-on: ubuntu-latest

    steps:
      - name: Handle with Comvent
        uses: rytswd/comvent@v0.3
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comvent-chatbot.yaml

      # The below only runs when Comvent finds matching comment.
      # This assumes that Comvent config holding 'command-random' as a keyword.
      - if: steps.comvent.outputs.command-random != ''
        name: Handle random event
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # An example of responding to a comment.
          script: |
            const comment = `Command \`/random\` was triggered by the comment`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

      #
      # You can repeat similar handling based on the Comvent config.
      #

```
